#!/usr/bin/env bash
echo "==sync"
# exits immediately if any command returns a non-zero status
set -e

# Check for bucket name
if [ -z "$1" ]; then
    echo "Must be a bucket name eg. ./bucket my-bucket"
    exit 1
fi

# Check for filename prefix
if [ -z "$2" ]; then
    echo "Must be a bucket name eg. ./bucket my-bucket"
    exit 1
fi
BUCKET_NAME=$1
FILENAME_PREFIX=$2

# where we'll store the files
OUTPUT_DIR="/tmp/s3/bash-scripts"

# remove folder if ti already exists
rm -r $OUTPUT_DIR

# create output folder
mkdir -p $OUTPUT_DIR

# generate a random number
# to determine how many files to create
NUM_FILES=$((RANDOM % 6 + 5))

for ((i=1; i <= $NUM_FILES; i++)); do
    # generate random file name
    FILENAME="$OUTPUT_DIR/{$FILENAME_PREFIX}_$i.txt"

    # generate random data and write to the file
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 +1)) 2>/dev/null
    echo "Created $FILENAME"
done

echo "Files created in $OUTPUT_DIR:"
ls "$OUTPUT_DIR"

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files